name: Test

# Executes on all branches
on: push

# Run all Jest tests
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the source code"
        uses: actions/checkout@v4
      - name: "Setup Node.JS"
        uses: actions/setup-node@v4
      - name: "Install all app packages"
        run: npm install
      - name: "Run Prettier to format code"
        run: npm test
